name = "centrale"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "."
binding = "ASSETS"

[[routes]]
pattern = "lacentraledesaffaires.fr/*"
zone_name = "lacentraledesaffaires.fr"

[[routes]]
pattern = "www.lacentraledesaffaires.fr/*"
zone_name = "lacentraledesaffaires.fr"
